# This workflow will release a Docker Container Image to Docker Hub when a new release is published on GitHub
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: DockerCI
on: 
  release: 
    types: [published]
    
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2 
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up JDK 1.14 
      uses: actions/setup-java@v1
      with: 
        java-version: 1.14 
    - name: Build with Maven 
      run: | 
        curl -O http://download.geonames.org/export/dump/allCountries.zip
        unzip allCountries.zip
        mvn -B clean package -Dmaven.test.skip=true
        java -Xmx4096m -jar -Dspring.profiles.active=Build target/clavin-rest.jar
        mvn -B clean package
        tar -czvf IndexDirectory.tar.gz IndexDirectory
        mvn dockerfile:build@push-version