# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: FeatureCI
on: 
  push: 
    branches:
      - '*'
  pull_request: 
    branches: 
      - '*'
    
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2 
    - name: Set up JDK 1.14 
      uses: actions/setup-java@v1
      with: 
        java-version: 1.14 
    - name: Build with Maven 
      run: | 
        curl -O http://download.geonames.org/export/dump/allCountries.zip 
        unzip allCountries.zip 
        mvn -B clean package
        java -Xmx4096m -jar -Dspring.profiles.active=Build target/clavin-rest.jar
        java -Xmx2048m -jar target/clavin-rest.jar 
        curl -s --data @src/test/resources/Somalia-doc.txt --header "Content-Type: text/plain" http://localhost:9090/api/v1/geotag